from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["privacy"])

PRIVACY_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Privacy Policy — ScamVax</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #0f172a; color: #f1f5f9; min-height: 100vh;
      padding: 32px 24px 64px;
    }
    .container { max-width: 720px; margin: 0 auto; }
    .lang-bar {
      display: flex; justify-content: flex-end; margin-bottom: 24px; gap: 8px;
    }
    .lang-btn {
      background: #1e293b; color: #94a3b8; border: 1px solid #334155;
      padding: 6px 14px; border-radius: 6px; cursor: pointer; font-size: 13px;
      transition: all .2s;
    }
    .lang-btn.active { background: #6366f1; color: white; border-color: #6366f1; }
    .badge {
      background: #6366f1; color: white; font-size: 11px; font-weight: 700;
      padding: 3px 10px; border-radius: 99px; display: inline-block; margin-bottom: 12px;
      letter-spacing: .04em; text-transform: uppercase;
    }
    h1 { font-size: 28px; font-weight: 800; margin-bottom: 6px; line-height: 1.2; }
    .meta { color: #64748b; font-size: 13px; margin-bottom: 40px; }
    h2 {
      font-size: 17px; font-weight: 700; color: #c7d2fe;
      margin: 36px 0 14px; padding-left: 14px;
      border-left: 3px solid #6366f1;
    }
    p { color: #cbd5e1; line-height: 1.75; margin-bottom: 12px; font-size: 15px; }
    ul { padding-left: 20px; margin-bottom: 12px; }
    li { color: #cbd5e1; line-height: 1.7; margin-bottom: 6px; font-size: 15px; }
    li strong { color: #f1f5f9; }
    .table-wrap { overflow-x: auto; margin-bottom: 16px; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th {
      background: #1e293b; color: #94a3b8; text-align: left;
      padding: 10px 14px; font-weight: 600; border-bottom: 1px solid #334155;
    }
    td {
      padding: 10px 14px; border-bottom: 1px solid #1e293b; color: #cbd5e1;
      vertical-align: top;
    }
    tr:last-child td { border-bottom: none; }
    .highlight {
      background: #1e293b; border-radius: 10px; padding: 16px 20px;
      margin-bottom: 16px; border: 1px solid #334155;
    }
    .highlight p { margin: 0; }
    a { color: #818cf8; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .footer {
      margin-top: 48px; padding-top: 24px; border-top: 1px solid #1e293b;
      text-align: center; font-size: 13px; color: #475569;
    }
    .panel-en, .panel-zh { display: none; }
    .panel-en.active, .panel-zh.active { display: block; }
  </style>
</head>
<body>
<div class="container">
  <div class="lang-bar">
    <button class="lang-btn active" id="btn-en" onclick="switchLang('en')">English</button>
    <button class="lang-btn" id="btn-zh" onclick="switchLang('zh')">中文</button>
  </div>
  <div class="panel-en active" id="panel-en">
    <span class="badge">Privacy Policy</span>
    <h1>ScamVax Privacy Policy</h1>
    <p class="meta">Effective date: 22 February 2026 &nbsp;·&nbsp; Last updated: 22 February 2026</p>
    <p>ScamVax ("we", "our", or "the App") is an anti-scam education tool. This policy explains what data we collect, why, how it is used, and your rights. We keep data collection to the minimum required for the App to function.</p>
    <h2>1. What Data We Collect</h2>
    <div class="table-wrap"><table>
      <tr><th>Category</th><th>What exactly</th><th>Source</th></tr>
      <tr><td><strong>Audio Data</strong></td><td>A voice recording you choose to submit for generating an AI-cloned voice challenge. The original recording is <em>never stored</em>; it is processed in memory and discarded immediately after synthesis.</td><td>Provided by you in-app</td></tr>
      <tr><td><strong>Device Identifier</strong></td><td>A random identifier generated and stored on your device (not the system advertising ID / IDFA). Used solely for rate-limiting: preventing abuse by limiting how many challenges one device may create.</td><td>Generated by the App on first launch</td></tr>
      <tr><td><strong>Advertising Data</strong></td><td>We declare this category in App Store Connect because the App's privacy label covers potential future use. Currently, we do <strong>not</strong> use any advertising SDK, display ads, or share data with advertising networks. If this changes, we will update this policy before doing so.</td><td>—</td></tr>
    </table></div>
    <p>We do <strong>not</strong> collect names, email addresses, phone numbers, location, contacts, browsing history, or health data.</p>
    <h2>2. Why We Collect It (Purpose)</h2>
    <ul>
      <li><strong>Audio Data</strong> — to generate an AI voice-clone of your recording so you can share a realistic "could you tell?" challenge with family members. The original recording is discarded the moment synthesis completes.</li>
      <li><strong>Device Identifier</strong> — to enforce a per-device creation limit and prevent service abuse (rate limiting / anti-fraud). It is not used for analytics, profiling, or advertising.</li>
    </ul>
    <h2>3. Tracking &amp; Cross-App Data Use</h2>
    <div class="highlight"><p>We do <strong>not</strong> track you across third-party apps or websites. The device identifier we use is not the system advertising ID (IDFA) and is not shared with any advertising or analytics network. No data is used for targeted advertising.</p></div>
    <h2>4. Third-Party Processors</h2>
    <p>We use the following service providers who may process your data on our behalf:</p>
    <div class="table-wrap"><table>
      <tr><th>Provider</th><th>Role</th><th>Data involved</th><th>Privacy info</th></tr>
      <tr><td><strong>Alibaba Cloud (DashScope)</strong></td><td>Voice synthesis API — your audio is sent for cloning and the synthesised audio is returned.</td><td>Audio (in transit, for synthesis only)</td><td><a href="https://www.alibabacloud.com/en/privacy-policy" target="_blank" rel="noopener">Privacy Policy</a></td></tr>
      <tr><td><strong>Cloudflare (R2)</strong></td><td>Object storage — the AI-generated audio file is stored here and served via CDN to challenge link visitors.</td><td>AI-generated audio only</td><td><a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener">Privacy Policy</a></td></tr>
      <tr><td><strong>Render</strong></td><td>Backend hosting — the API server runs on Render's infrastructure.</td><td>API request data (audio, device ID)</td><td><a href="https://render.com/privacy" target="_blank" rel="noopener">Privacy Policy</a></td></tr>
    </table></div>
    <p>We do not sell your data. We do not share data with any party for advertising purposes.</p>
    <h2>5. Data Retention &amp; Deletion</h2>
    <ul>
      <li><strong>Original recording</strong> — discarded in memory immediately after synthesis. Never written to disk or storage.</li>
      <li><strong>AI-generated audio</strong> — stored in Cloudflare R2 and automatically deleted after <strong>72 hours</strong> or <strong>50 visits</strong> to the challenge link, whichever occurs first. Our server runs a cleanup job every 30 minutes.</li>
      <li><strong>Device identifier</strong> — stored in our database linked to challenge records; deleted when its associated challenge expires (see above).</li>
      <li><strong>Server logs</strong> — retained for up to 30 days for operational purposes, then purged.</li>
    </ul>
    <h2>6. Your Rights &amp; Deletion Requests</h2>
    <p>Because we do not require account creation, we hold no user profile or account data. If you wish to request early deletion of a specific challenge (AI audio) you created, or have any privacy concern, please contact us:</p>
    <div class="highlight"><p>📧 <a href="mailto:junqiangguo177@gmail.com">junqiangguo177@gmail.com</a></p></div>
    <p>Include a description of your request and, if possible, the challenge URL. We will respond within 30 days.</p>
    <p>Depending on your jurisdiction you may have rights to access, correct, or delete your personal data (e.g. under GDPR, CCPA, or Australian Privacy Act). We will honour reasonable requests.</p>
    <h2>7. Security</h2>
    <ul>
      <li>All data is transmitted over <strong>HTTPS / TLS</strong>.</li>
      <li>Cloudflare R2 storage uses server-side encryption at rest.</li>
      <li>Access to our backend and storage is restricted to authorised personnel via least-privilege credentials.</li>
      <li>Your original recording is processed in memory only and is never written to persistent storage.</li>
    </ul>
    <h2>8. Children's Privacy</h2>
    <p>ScamVax is not directed at children under 13 (or 16 in the EU). We do not knowingly collect personal data from children. If you believe we have inadvertently done so, please contact us and we will delete it promptly.</p>
    <h2>9. Changes to This Policy</h2>
    <p>We may update this policy from time to time. We will update the "Last updated" date above. Continued use of the App after changes constitutes acceptance of the revised policy.</p>
    <h2>10. Contact</h2>
    <p>For privacy-related questions or requests:</p>
    <div class="highlight"><p>📧 <a href="mailto:junqiangguo177@gmail.com">junqiangguo177@gmail.com</a><br/><span style="color:#64748b;font-size:13px;">ScamVax — anti-scam education platform</span></p></div>
  </div>
  <div class="panel-zh" id="panel-zh">
    <span class="badge">隐私政策</span>
    <h1>ScamVax 隐私政策</h1>
    <p class="meta">生效日期：2026年2月22日 &nbsp;·&nbsp; 最后更新：2026年2月22日</p>
    <p>ScamVax（以下简称"我们"或"本应用"）是一款防骗教育工具。本政策说明我们收集哪些数据、为何收集、如何使用，以及您的权利。我们将数据收集限制在应用正常运行所必需的最低范围。</p>
    <h2>1. 我们收集哪些数据</h2>
    <div class="table-wrap"><table>
      <tr><th>类别</th><th>具体内容</th><th>来源</th></tr>
      <tr><td><strong>音频数据</strong></td><td>您在应用内主动提交的语音录音，用于生成 AI 声音克隆挑战。<em>原始录音从不存储</em>——合成完成后立即在内存中丢弃。</td><td>您在应用内提供</td></tr>
      <tr><td><strong>设备标识符</strong></td><td>由应用在首次启动时随机生成并本地保存的 ID（非系统广告标识符 IDFA）。仅用于频率限制：防止单一设备在短时间内创建过多挑战。</td><td>应用首次启动时生成</td></tr>
      <tr><td><strong>广告数据</strong></td><td>我们在 App Store Connect 隐私标签中声明了该类别，以覆盖潜在的未来场景。<strong>目前</strong>，我们不集成任何广告 SDK、不投放广告、不与广告网络共享数据。如有变更，我们将在实施前更新本政策。</td><td>—</td></tr>
    </table></div>
    <p>我们<strong>不</strong>收集姓名、邮箱、手机号、位置、通讯录、浏览记录或健康数据。</p>
    <h2>2. 收集目的</h2>
    <ul>
      <li><strong>音频数据</strong> — 生成您声音的 AI 克隆版本，以便您将"你能分辨吗？"挑战分享给家人。原始录音在合成完成后立即丢弃。</li>
      <li><strong>设备标识符</strong> — 执行每台设备的创建频率限制，防止服务滥用（频控 / 反作弊）。不用于数据分析、用户画像或广告。</li>
    </ul>
    <h2>3. 跨应用追踪（Tracking）</h2>
    <div class="highlight"><p>我们<strong>不</strong>通过跨第三方应用或网站的方式追踪您。我们使用的设备标识符并非系统广告 ID（IDFA），也不会与任何广告或统计网络共享。没有任何数据用于定向广告。</p></div>
    <h2>4. 第三方数据处理方</h2>
    <p>我们使用以下服务商代我们处理数据：</p>
    <div class="table-wrap"><table>
      <tr><th>服务商</th><th>角色</th><th>涉及数据</th><th>隐私信息</th></tr>
      <tr><td><strong>阿里云（DashScope）</strong></td><td>语音合成 API — 您的音频在 API 调用期间发送至阿里云进行声音克隆，合成后返回结果。</td><td>音频（传输中，仅用于合成）</td><td><a href="https://www.alibabacloud.com/en/privacy-policy" target="_blank" rel="noopener">隐私政策</a></td></tr>
      <tr><td><strong>Cloudflare（R2）</strong></td><td>对象存储 — AI 生成的音频存储于此，通过 CDN 分发给访问挑战链接的用户。</td><td>仅 AI 生成音频</td><td><a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener">隐私政策</a></td></tr>
      <tr><td><strong>Render</strong></td><td>后端托管 — API 服务器运行于 Render 基础设施上。</td><td>API 请求数据（音频、设备 ID）</td><td><a href="https://render.com/privacy" target="_blank" rel="noopener">隐私政策</a></td></tr>
    </table></div>
    <p>我们不出售您的数据，也不以任何形式将数据共享给广告方。</p>
    <h2>5. 数据保留与删除</h2>
    <ul>
      <li><strong>原始录音</strong> — 在内存中处理，合成完成后立即丢弃，从不写入磁盘或持久化存储。</li>
      <li><strong>AI 生成音频</strong> — 存储于 Cloudflare R2，在挑战链接被访问 <strong>50 次</strong>或距创建 <strong>72 小时</strong>（以先达到者为准）后自动删除。服务器每 30 分钟执行一次清理任务。</li>
      <li><strong>设备标识符</strong> — 存储于我们的数据库，与挑战记录绑定；挑战到期（见上文）时一并删除。</li>
      <li><strong>服务器日志</strong> — 出于运营需要保留最多 30 天，随后清除。</li>
    </ul>
    <h2>6. 您的权利与删除请求</h2>
    <p>由于本应用无需注册账号，我们不持有用户档案或账号信息。如需提前删除您创建的某个挑战（AI 音频），或有其他隐私问题，请联系我们：</p>
    <div class="highlight"><p>📧 <a href="mailto:junqiangguo177@gmail.com">junqiangguo177@gmail.com</a></p></div>
    <p>请在邮件中描述您的请求，如方便请附上挑战链接。我们将在 30 天内回复。</p>
    <p>根据您所在地区适用的法律（例如 GDPR、CCPA、澳大利亚《隐私法》），您可能享有访问、更正或删除个人数据的权利。我们将合理响应此类请求。</p>
    <h2>7. 安全措施</h2>
    <ul>
      <li>所有数据传输均通过 <strong>HTTPS / TLS</strong> 加密。</li>
      <li>Cloudflare R2 存储使用服务端静态加密。</li>
      <li>后端和存储的访问权限受最小权限原则控制，仅授权人员可访问。</li>
      <li>原始录音仅在内存中处理，不写入任何持久化存储。</li>
    </ul>
    <h2>8. 儿童隐私</h2>
    <p>ScamVax 不面向 13 岁以下（欧盟地区为 16 岁以下）的儿童。我们不会有意收集儿童的个人数据。如您认为我们无意中收集了儿童数据，请联系我们，我们将立即删除。</p>
    <h2>9. 政策变更</h2>
    <p>我们可能不时更新本政策，届时将同步更新上方的"最后更新"日期。在变更后继续使用本应用，即视为接受修订后的政策。</p>
    <h2>10. 联系方式</h2>
    <p>如有任何隐私相关问题或请求：</p>
    <div class="highlight"><p>📧 <a href="mailto:junqiangguo177@gmail.com">junqiangguo177@gmail.com</a><br/><span style="color:#64748b;font-size:13px;">ScamVax — 家庭防骗教育平台</span></p></div>
  </div>
  <div class="footer">© 2026 ScamVax &nbsp;·&nbsp; <a href="/privacy">Privacy Policy</a></div>
</div>
<script>
  function switchLang(lang) {
    document.getElementById('panel-en').classList.toggle('active', lang === 'en');
    document.getElementById('panel-zh').classList.toggle('active', lang === 'zh');
    document.getElementById('btn-en').classList.toggle('active', lang === 'en');
    document.getElementById('btn-zh').classList.toggle('active', lang === 'zh');
    localStorage.setItem('sv_privacy_lang', lang);
  }
  (function() {
    var saved = localStorage.getItem('sv_privacy_lang');
    var browserLang = (navigator.language || '').toLowerCase();
    if (saved === 'zh' || saved === 'en') { switchLang(saved); }
    else if (browserLang.startsWith('zh')) { switchLang('zh'); }
  })();
</script>
</body>
</html>"""


@router.get("/privacy", response_class=HTMLResponse)
async def privacy_page():
    """隐私政策页面 (双语 EN/ZH)"""
    return HTMLResponse(content=PRIVACY_PAGE)
